### ISSUE TITLE
Invalid dates in to.obo as per OBO API

### ISSUE THREAD

**Issue by sammyjava** [Planteome/plant-trait-ontology#431]
The OBO Java API errors out when loading the current to.obo file due to a date format:
```
Caused by: Error: Badly formatted creation date: 2017-07-10
on line: 21480 of file:/home/shokin/plant-trait-ontology/to.obo
charnum: 14
line: creation_date: 2017-07-10
	at org.obo.dataadapter.OBOParseEngine.translateException(OBOParseEngine.java:1444)
	at org.obo.dataadapter.OBOParseEngine.translateAndThrow(OBOParseEngine.java:1436)
	at org.obo.dataadapter.OBOParseEngine.doParse(OBOParseEngine.java:402)
	at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:48)
	at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:72)
	at org.obo.dataadapter.OBOFileAdapter.doOperation(OBOFileAdapter.java:273)
```
Apparently the OBO API requires the full form, like `2012-04-19T10:36:57Z`

**Comment by cmungall** [comment]
Sorry, which OBO API do you mean?

It looks like this may be the OE one. In which case I suggest migrating. 

The java lib here will accept all forms of OWL, including obo format, and json
https://github.com/geneontology/obographs/

**Comment by sammyjava** [comment]
Ahh, I'll give that a shot. I was using the obo.jar that comes with InterMine, which errors the same as the current obo-2.0.jar that is on the Maven repo (https://mvnrepository.com/artifact/obo/obo/2.0) and will therefore likely continue to be used by InterMine; but I can override it with your suggestion. I'll close this if it works.

**Comment by cooperl09** [comment]
Those have been fixed in the editors version (plant-trait-ontology.obo), so they will be in to.obo once we do the next release (soon!).

**Comment by sammyjava** [comment]
Cool, closing this, then.
